import { addDays, assertStrictInputObject, normalizeEmail, normalizeRequiredId, normalizeRequiredText, normalizeSha256, normalizeTimestamp } from './validation.js'

export const STUDENT_INVITATION_SCHEMA_VERSION = 1
export const STUDENT_INVITATION_STATUS = Object.freeze({ PENDING: 'PENDING', ACCEPTED: 'ACCEPTED', REVOKED: 'REVOKED', EXPIRED: 'EXPIRED' })
const INPUT_FIELDS = ['inviteId','teacherId','email','studentDisplayNameOrNickname','tokenHash','createdAt']
function assertPending(record) { if (!record || record.schemaVersion !== STUDENT_INVITATION_SCHEMA_VERSION || record.status !== 'PENDING') throw new Error('StudentInvitation must be PENDING for this transition.') }
export function createStudentInvitation(input = {}) { assertStrictInputObject(input, INPUT_FIELDS, 'StudentInvitation'); const createdAt = normalizeTimestamp(input.createdAt, 'createdAt'); return Object.freeze({ schemaVersion: STUDENT_INVITATION_SCHEMA_VERSION, inviteId: normalizeRequiredId(input.inviteId,'inviteId'), teacherId: normalizeRequiredId(input.teacherId,'teacherId'), emailNormalized: normalizeEmail(input.email), studentDisplayNameOrNickname: normalizeRequiredText(input.studentDisplayNameOrNickname,'studentDisplayNameOrNickname',200), status: STUDENT_INVITATION_STATUS.PENDING, tokenHash: normalizeSha256(input.tokenHash), createdAt, expiresAt: addDays(createdAt,7), acceptedAt: null, revokedAt: null, studentId: null }) }
export function acceptStudentInvitation(record, input = {}) { assertPending(record); assertStrictInputObject(input,['studentId','acceptedAt'],'StudentInvitation acceptance'); const acceptedAt = normalizeTimestamp(input.acceptedAt,'acceptedAt'); if (acceptedAt > record.expiresAt) throw new Error('StudentInvitation is expired and cannot be accepted.'); return Object.freeze({ ...record, status: STUDENT_INVITATION_STATUS.ACCEPTED, studentId: normalizeRequiredId(input.studentId,'studentId'), acceptedAt }) }
export function revokeStudentInvitation(record, revokedAt) { assertPending(record); return Object.freeze({ ...record, status: STUDENT_INVITATION_STATUS.REVOKED, revokedAt: normalizeTimestamp(revokedAt,'revokedAt') }) }
export function expireStudentInvitation(record, expiredAt) { assertPending(record); const at=normalizeTimestamp(expiredAt,'expiredAt'); if (at < record.expiresAt) throw new Error('StudentInvitation cannot expire before expiresAt.'); return Object.freeze({ ...record, status: STUDENT_INVITATION_STATUS.EXPIRED }) }
