import assert from 'node:assert/strict'
import test from 'node:test'
function fakeFramework(){const routes={get:new Map(),post:new Map()};const router={get:(p,h)=>{routes.get.set(p,h);return router},post:(p,h)=>{routes.post.set(p,h);return router}};const app={uses:[],get:(p,h)=>{routes.get.set(p,h);return app},use(x){this.uses.push(x);return this},listen(port,cb){cb?.();let closed=false;return {close(done){closed=true;done?.()},get closed(){return closed}}}};return {app,router,routes,framework:{createApp:()=>app,createRouter:()=>router,jsonMiddleware:()=>((_req,_res,next)=>next?.())}}}
function response(){return {statusCode:200,body:null,status(code){this.statusCode=code;return this},json(body){this.body=body;return this}}}
function minimalAdapters(framework){const emptyRepo={async findPendingByTeacherAndEmail(){return null},async findByTokenHash(){return null},async getById(){return null},async listByTeacher(){return []},async create(v){return v},async replace(_a,b){return b}};const accountRepo={async findByFirebaseUid(){return null},async findByStudentId(){return null},async createActivating(v){return v},async markActive(){throw new Error('not found')}};const relRepo={async beginActivation(v){return v},async markActive(){throw new Error('not found')},async getBySourceInviteId(){return null},async listByTeacher(){return []}};const usageRepo={async recordSessionOnce(){return {isNew:true,totalSessions:1,lastSessionAt:'2026-10-07T18:00:00.000Z'}},async getSummary(id){return {studentId:id,totalSessions:0,lastSessionAt:null}}};return {framework,tokenVerifier:{async verifyIdToken(){return {uid:'uid-a',email:'student@example.com'}}},teacherIdentityResolver:{async resolveTeacher(){return {teacherId:'teacher-a',active:true}}},authDirectory:{async accountExistsByEmail(){return false}},invitationRepository:emptyRepo,studentAccountRepository:accountRepo,relationshipRepository:relRepo,usageRepository:usageRepo,presenceReader:{async getPresenceByFirebaseUid(){return {state:'UNKNOWN',lastOnlineAt:null}}}}}

test('composition exposes bounded health and close is deterministic', async () => {const {createStudentAccountService}=await import('../../src/composition.js');const f=fakeFramework();const service=createStudentAccountService({config:{mode:'test',invitationBaseUrl:'https://student.example.test'},adapters:minimalAdapters(f.framework)});assert.equal(typeof service.close,'function');const res=response();await f.routes.get.get('/health')({},res);assert.deepEqual(res.body,{service:'st-student-account-service',status:'ok'});assert.equal('projectId' in res.body,false);assert.equal('provider' in res.body,false);await service.close();await service.close()})

test('production composition requires an explicit Secure Delivery authority adapter', async () => {const {createStudentAccountService}=await import('../../src/composition.js');const f=fakeFramework();assert.throws(()=>createStudentAccountService({config:{mode:'production',invitationBaseUrl:'https://student.example.test'},adapters:minimalAdapters(f.framework)}),/Secure Delivery authority|authority/i)})

test('non-production composition keeps activation closed when authority is absent', async () => {const {createStudentAccountService}=await import('../../src/composition.js');const f=fakeFramework();const service=createStudentAccountService({config:{mode:'test',invitationBaseUrl:'https://student.example.test'},adapters:minimalAdapters(f.framework)});assert.equal(service.activationEnabled,false);const handler=f.routes.post.get('/api/student-accounts/v1/student/invitations/accept');assert.equal(typeof handler,'function');const res=response();await handler({headers:{authorization:'Bearer token-a'},body:{inviteToken:'secret-a'}},res);assert.notEqual(res.statusCode,200)})
