import assert from 'node:assert/strict'
import test from 'node:test'
import { initializeApp, deleteApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import { createStudentInvitation } from '../../src/domain/studentInvitation.js'
import { createStudentAccount } from '../../src/domain/studentAccount.js'
import { createTeacherStudentRelationship } from '../../src/domain/teacherStudentRelationship.js'
import { createFirestoreInvitationRepository } from '../../src/adapters/firebase/firestoreInvitationRepository.js'
import { createFirestoreStudentAccountRepository } from '../../src/adapters/firebase/firestoreStudentAccountRepository.js'
import { createFirestoreRelationshipRepository } from '../../src/adapters/firebase/firestoreRelationshipRepository.js'
const PROJECT_ID='demo-st-student-account'
function appName(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function cleanup(db){for(const name of ['studentInvitations','studentAccounts','teacherStudentRelationships','studentUsage']){try{await db.recursiveDelete(db.collection(name))}catch{}}}

test('Firestore invitation adapter enforces uniqueness lookup and optimistic replacement',async()=>{const app=initializeApp({projectId:PROJECT_ID},appName('invite'));const db=getFirestore(app);const repo=createFirestoreInvitationRepository({db});try{const row=createStudentInvitation({inviteId:'invite-a',teacherId:'teacher-a',email:'student@example.com',studentDisplayNameOrNickname:'Ayşe',tokenHash:'a'.repeat(64),createdAt:'2026-10-07T18:00:00.000Z'});await repo.create(row);assert.equal((await repo.getById('invite-a')).inviteId,'invite-a');assert.equal((await repo.findByTokenHash('a'.repeat(64))).inviteId,'invite-a');await assert.rejects(()=>repo.create(createStudentInvitation({inviteId:'invite-b',teacherId:'teacher-a',email:'student@example.com',studentDisplayNameOrNickname:'Ayşe',tokenHash:'b'.repeat(64),createdAt:'2026-10-07T18:01:00.000Z'})),/pending|conflict/i);const revoked=Object.freeze({...row,status:'REVOKED',revokedAt:'2026-10-07T19:00:00.000Z'});await repo.replace(row,revoked);await assert.rejects(()=>repo.replace(row,Object.freeze({...row,status:'EXPIRED'})),/optimistic conflict/i)}finally{await cleanup(db);await deleteApp(app)}})

test('Firestore account and relationship adapters converge on one uid and source invite',async()=>{const app=initializeApp({projectId:PROJECT_ID},appName('activation'));const db=getFirestore(app);const accounts=createFirestoreStudentAccountRepository({db});const relationships=createFirestoreRelationshipRepository({db});try{const account=createStudentAccount({studentId:'student-a',firebaseUid:'uid-a',email:'student@example.com',createdAt:'2026-10-07T18:00:00.000Z',active:false});assert.equal((await accounts.createActivating(account)).studentId,'student-a');assert.equal((await accounts.createActivating(account)).studentId,'student-a');const activeAccount=await accounts.markActive('student-a');assert.equal(activeAccount.active,true);assert.equal((await accounts.findByFirebaseUid('uid-a')).studentId,'student-a');const rel=createTeacherStudentRelationship({relationshipId:'rel-a',teacherId:'teacher-a',studentId:'student-a',displayNameOrNickname:'Ayşe',active:false,createdAt:'2026-10-07T18:00:00.000Z',activatedAt:null,deactivatedAt:null,sourceInviteId:'invite-a'});assert.equal((await relationships.beginActivation(rel)).relationshipId,'rel-a');assert.equal((await relationships.beginActivation(rel)).relationshipId,'rel-a');const activeRel=await relationships.markActive('rel-a','2026-10-07T18:01:00.000Z');assert.equal(activeRel.active,true);assert.equal((await relationships.listByTeacher('teacher-a')).length,1)}finally{await cleanup(db);await deleteApp(app)}})
