import { createInvitationService } from './application/createInvitation.js'
import { resolveInvitationService } from './application/resolveInvitation.js'
import { revokeInvitationService } from './application/revokeInvitation.js'
import { acceptInvitationService } from './application/acceptInvitation.js'
import { recordStudentSessionService } from './application/recordStudentSession.js'
import { listTeacherStudentsService } from './application/listTeacherStudents.js'
import { registerStudentAccountRoutes } from './http/router.js'
import { createSystemClock } from './ports/clock.js'
import { createNodeTokenGenerator } from './ports/tokenGenerator.js'
function assertFramework(framework){for(const method of ['createApp','createRouter'])if(!framework||typeof framework[method]!=='function')throw new TypeError(`framework must provide ${method}().`);return framework}
function closedAuthority(){return Object.freeze({async activateStudent(){throw new Error('secure-delivery-authority-unavailable')}})}
function assertConfig(config){if(!config||typeof config!=='object')throw new TypeError('config is required.');if(!['test','emulator','production'].includes(config.mode))throw new TypeError('config.mode must be test, emulator, or production.');if(typeof config.invitationBaseUrl!=='string'||!/^https:\/\//.test(config.invitationBaseUrl))throw new TypeError('config.invitationBaseUrl must be an https URL.');return config}
export function createStudentAccountService({config,adapters={}}={}){const safeConfig=assertConfig(config);if(safeConfig.mode==='production'&&!adapters.secureDeliveryAuthority)throw new Error('production Secure Delivery authority adapter is required.');const framework=assertFramework(adapters.framework);const app=framework.createApp();const router=framework.createRouter();if(!app||typeof app.use!=='function'||typeof app.get!=='function')throw new TypeError('framework app must provide use() and get().');const clock=adapters.clock??createSystemClock();const tokenGenerator=adapters.tokenGenerator??createNodeTokenGenerator();const authority=adapters.secureDeliveryAuthority??closedAuthority();const createInvitation=createInvitationService({repository:adapters.invitationRepository,clock,tokenGenerator,invitationBaseUrl:safeConfig.invitationBaseUrl});const resolveInvitation=resolveInvitationService({repository:adapters.invitationRepository,authDirectory:adapters.authDirectory,clock,tokenGenerator});const revokeInvitation=revokeInvitationService({repository:adapters.invitationRepository,clock});const acceptInvitation=acceptInvitationService({invitationRepository:adapters.invitationRepository,studentAccountRepository:adapters.studentAccountRepository,relationshipRepository:adapters.relationshipRepository,secureDeliveryAuthority:authority,clock,tokenGenerator});const recordStudentSession=recordStudentSessionService({tokenVerifier:adapters.tokenVerifier,studentAccountRepository:adapters.studentAccountRepository,usageRepository:adapters.usageRepository,clock});const listTeacherStudents=listTeacherStudentsService({invitationRepository:adapters.invitationRepository,studentAccountRepository:adapters.studentAccountRepository,relationshipRepository:adapters.relationshipRepository,usageRepository:adapters.usageRepository,presenceReader:adapters.presenceReader});if(typeof framework.jsonMiddleware==='function')app.use(framework.jsonMiddleware());app.get('/health',(_req,res)=>res.status?.(200)?.json?res.status(200).json({service:'st-student-account-service',status:'ok'}):res.json({service:'st-student-account-service',status:'ok'}));registerStudentAccountRoutes({router,tokenVerifier:adapters.tokenVerifier,teacherIdentityResolver:adapters.teacherIdentityResolver,createInvitation,resolveInvitation,revokeInvitation,acceptInvitation,recordStudentSession,listTeacherStudents});app.use(router);let closed=false;return Object.freeze({app,router,activationEnabled:Boolean(adapters.secureDeliveryAuthority),async close(){if(closed)return;closed=true;if(typeof adapters.close==='function')await adapters.close()}})}
