import { pathToFileURL } from 'node:url'
import { createStudentAccountService } from './composition.js'
import { createFirebaseAdmin } from './adapters/firebase/firebaseAdmin.js'
import { createFirebaseTokenVerifier } from './adapters/firebase/firebaseTokenVerifier.js'
import { createFirebaseAuthDirectory } from './adapters/firebase/firebaseAuthDirectory.js'
import { createFirestoreInvitationRepository } from './adapters/firebase/firestoreInvitationRepository.js'
import { createFirestoreStudentAccountRepository } from './adapters/firebase/firestoreStudentAccountRepository.js'
import { createFirestoreRelationshipRepository } from './adapters/firebase/firestoreRelationshipRepository.js'
import { createFirestoreUsageRepository } from './adapters/firebase/firestoreUsageRepository.js'
import { createRealtimePresenceReader } from './adapters/firebase/realtimePresenceReader.js'
function required(env,name){const value=env?.[name];if(typeof value!=='string'||!value.trim())throw new TypeError(`${name} is required.`);return value.trim()}
export function buildRuntimeConfig(env=process.env){const projectId=required(env,'FIREBASE_PROJECT_ID');const databaseURL=required(env,'FIREBASE_DATABASE_URL');const invitationBaseUrl=required(env,'INVITATION_BASE_URL');const emulator=Boolean(env.FIRESTORE_EMULATOR_HOST||env.FIREBASE_AUTH_EMULATOR_HOST||env.FIREBASE_DATABASE_EMULATOR_HOST);const port=Number(env.PORT??'8787');if(!Number.isSafeInteger(port)||port<1||port>65535)throw new TypeError('PORT must be a valid TCP port.');return Object.freeze({mode:emulator?'emulator':'production',projectId,databaseURL,invitationBaseUrl,port,emulatorHosts:Object.freeze({firestore:env.FIRESTORE_EMULATOR_HOST??null,auth:env.FIREBASE_AUTH_EMULATOR_HOST??null,database:env.FIREBASE_DATABASE_EMULATOR_HOST??null})})}
async function createExpressFramework(){const module=await import('express');const express=module.default??module;return Object.freeze({createApp:()=>express(),createRouter:()=>express.Router(),jsonMiddleware:()=>express.json({limit:'16kb'})})}
export async function createRuntimeService({env=process.env,overrides={}}={}){const config=buildRuntimeConfig(env);const firebase=overrides.firebase??await createFirebaseAdmin({projectId:config.projectId,databaseURL:config.databaseURL});const framework=overrides.framework??await createExpressFramework();const adapters={framework,tokenVerifier:overrides.tokenVerifier??createFirebaseTokenVerifier({auth:firebase.auth}),teacherIdentityResolver:overrides.teacherIdentityResolver??Object.freeze({async resolveTeacher(){return null}}),authDirectory:overrides.authDirectory??createFirebaseAuthDirectory({auth:firebase.auth}),invitationRepository:overrides.invitationRepository??createFirestoreInvitationRepository({db:firebase.firestore}),studentAccountRepository:overrides.studentAccountRepository??createFirestoreStudentAccountRepository({db:firebase.firestore}),relationshipRepository:overrides.relationshipRepository??createFirestoreRelationshipRepository({db:firebase.firestore}),usageRepository:overrides.usageRepository??createFirestoreUsageRepository({db:firebase.firestore}),presenceReader:overrides.presenceReader??createRealtimePresenceReader({database:firebase.database}),secureDeliveryAuthority:overrides.secureDeliveryAuthority};return createStudentAccountService({config:{mode:config.mode,invitationBaseUrl:config.invitationBaseUrl},adapters})}
export async function startHttpServer({env=process.env,overrides={}}={}){const config=buildRuntimeConfig(env);const service=await createRuntimeService({env,overrides});const server=await new Promise((resolve,reject)=>{const listener=service.app.listen(config.port,()=>resolve(listener));listener.on?.('error',reject)});let closed=false;return Object.freeze({service,server,async close(){if(closed)return;closed=true;await new Promise((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));await service.close()}})}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){startHttpServer().then(({server})=>{const address=server.address?.();const port=typeof address==='object'&&address?address.port:'configured';console.log(`st-student-account-service listening on ${port}`)}).catch(()=>{console.error('st-student-account-service failed to start');process.exitCode=1})}
