import assert from 'node:assert/strict'
import test from 'node:test'
import { createInvitationService } from '../../src/application/createInvitation.js'
import { acceptInvitationService } from '../../src/application/acceptInvitation.js'
import { recordStudentSessionService } from '../../src/application/recordStudentSession.js'
import { listTeacherStudentsService, toRosterProjection } from '../../src/application/listTeacherStudents.js'
import { createInMemoryInvitationRepository } from '../helpers/inMemoryInvitationRepository.js'
import { createInMemoryStudentAccountRepository } from '../helpers/inMemoryStudentAccountRepository.js'
import { createInMemoryRelationshipRepository } from '../helpers/inMemoryRelationshipRepository.js'
import { createInMemoryUsageRepository } from '../helpers/inMemoryUsageRepository.js'
import { createFakeSecureDeliveryAuthorityPort } from '../helpers/fakeSecureDeliveryAuthorityPort.js'

const clock={now:()=> '2026-10-08T18:00:00.000Z'}
function tokens(){let n=0;return{createInviteToken:()=>`raw-${++n}`,hashInviteToken:raw=>raw==='raw-1'?'a'.repeat(64):'b'.repeat(64),createDomainId:prefix=>`${prefix}-a`}}

test('invitation create confines raw token and server-private token hash',async()=>{const repo=createInMemoryInvitationRepository();const service=createInvitationService({repository:repo,clock,tokenGenerator:tokens(),invitationBaseUrl:'https://student.example'});const result=await service.execute({teacherId:'teacher-a',email:'Student@Example.com',displayNameOrNickname:'Ayşe'});assert.equal(result.invitationLink,'https://student.example/#/invite/raw-1');assert.equal('tokenHash' in result.invitation,false);const stored=await repo.getById(result.invitation.inviteId);assert.equal(stored.tokenHash,'a'.repeat(64));assert.equal(JSON.stringify(stored).includes('raw-1'),false)})

test('invitation acceptance activates exactly one stable student relationship after authority ack',async()=>{const invitations=createInMemoryInvitationRepository();const t=tokens();const created=await createInvitationService({repository:invitations,clock,tokenGenerator:t,invitationBaseUrl:'https://student.example'}).execute({teacherId:'teacher-a',email:'student@example.com',displayNameOrNickname:'Ayşe'});const accounts=createInMemoryStudentAccountRepository();const relationships=createInMemoryRelationshipRepository();const authority=createFakeSecureDeliveryAuthorityPort();const service=acceptInvitationService({invitationRepository:invitations,studentAccountRepository:accounts,relationshipRepository:relationships,secureDeliveryAuthority:authority,clock,tokenGenerator:t});const result=await service.execute({rawToken:'raw-1',authenticatedUser:{uid:'uid-a',email:'student@example.com'}});assert.equal(result.relationshipState,'ACTIVE');assert.equal((await invitations.getById(created.invitation.inviteId)).status,'ACCEPTED');assert.equal((await accounts.list()).length,1);assert.equal((await relationships.list()).length,1);assert.equal(authority.calls.length,1)})

test('usage session id is idempotent and teacher read model never leaks provider identity',async()=>{const accounts=createInMemoryStudentAccountRepository([{studentId:'student-a',firebaseUid:'uid-secret',email:'student@example.com',createdAt:'2026-10-07T18:00:00.000Z',active:true}]);const usage=createInMemoryUsageRepository();const session=recordStudentSessionService({tokenVerifier:{verifyIdToken:async()=>({uid:'uid-secret',email:'student@example.com'})},studentAccountRepository:accounts,usageRepository:usage,clock});const [a,b]=await Promise.all([session.execute({bearerToken:'good',clientSessionId:'session-a'}),session.execute({bearerToken:'good',clientSessionId:'session-a'})]);assert.equal(Math.max(a.totalSessions,b.totalSessions),1);const invitations=createInMemoryInvitationRepository();await invitations.seedRaw(Object.freeze({schemaVersion:1,inviteId:'invite-a',teacherId:'teacher-a',emailNormalized:'student@example.com',studentDisplayNameOrNickname:'Ayşe',status:'ACCEPTED',tokenHash:'a'.repeat(64),createdAt:'2026-10-07T18:00:00.000Z',expiresAt:'2026-10-14T18:00:00.000Z',acceptedAt:'2026-10-08T18:00:00.000Z',revokedAt:null,studentId:'student-a'}));const relationships=createInMemoryRelationshipRepository([{relationshipId:'rel-a',teacherId:'teacher-a',studentId:'student-a',displayNameOrNickname:'Ayşe',active:true,createdAt:'2026-10-07T18:00:00.000Z',activatedAt:'2026-10-08T18:00:00.000Z',deactivatedAt:null,sourceInviteId:'invite-a'}]);const rows=await listTeacherStudentsService({invitationRepository:invitations,studentAccountRepository:accounts,relationshipRepository:relationships,usageRepository:usage,presenceReader:{getPresenceByFirebaseUid:async()=>({state:'ONLINE',lastOnlineAt:null})}}).execute({teacherId:'teacher-a'});assert.equal(rows[0].totalSessions,1);assert.equal(rows[0].presenceState,'ONLINE');assert.equal(JSON.stringify(rows).includes('uid-secret'),false);assert.equal(JSON.stringify(rows).includes('student@example.com'),false);assert.deepEqual(toRosterProjection(rows[0]),{studentId:'student-a',displayNameOrNickname:'Ayşe',active:true})})
